spring:
  application:
    name: gatewayserver

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 5
            redis-rate-limiter.burstCapacity: 10
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY, INTERNAL_SERVER_ERROR
            methods: GET, POST
        - name: CircuitBreaker
          args:
            name: globalCB

      httpclient:
        connect-timeout: 1000
        response-timeout: 10s

resilience4j:
  circuitbreaker:
    instances:
      globalCB:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
