version: "3"

services:
  # MySQL Config for order service
  mysql-order:
    container_name: mysql-order
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_service
    volumes:
      - ./mysql_order:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

  # MySQL Config for inventory service
  mysql-inventory:
    container_name: mysql-inventory
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_service
    volumes:
      - ./mysql_inventory:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: always

  # MongoDB Config for product service
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  # Keycloak MySQL
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:latest
    volumes:
      - ./mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak

  # Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka Broker
  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # Eureka Discovery Server
  discovery-server:
    image: michaelmounir/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761

  # API Gateway
  api-gateway:
    image: michaelmounir/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8181:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://keycloak:8080/realms/spring-boot-microservices-realm
    depends_on:
      - discovery-server
      - keycloak

  # Product Service
  product-service:
    container_name: product-service
    image: michaelmounir/product-service:latest
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/product-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SERVER_PORT=8080
    depends_on:
      - mongo
      - discovery-server
      - api-gateway

  # Order Service
  order-service:
    container_name: order-service
    image: michaelmounir/order-service:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-order:3306/order_service?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_KAFKA_BOOTSTRAPSERVERS=broker:29092
    depends_on:
      - mysql-order
      - broker
      - discovery-server
      - api-gateway

  # Inventory Service
  inventory-service:
    container_name: inventory-service
    image: michaelmounir/inventory-service:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-inventory:3306/inventory_service?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      - mysql-inventory
      - discovery-server
      - api-gateway

  # Notification Service
  notification-service:
    container_name: notification-service
    image: michaelmounir/notification-service:latest
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
    depends_on:
      - broker
      - discovery-server
      - api-gateway
